Draw rectangular prisms for incomplete stabilizers
XanaduAI/flamingpy pull request #35
Opened 2022-05-12 19:54 UTC by sduquemesa

## Context for changes

Whenever there are incomplete stabilizer at boundaries, rectangular rather than cubic voxels are displayed.

- **New features**:
    * None
- **Bug fixes**: 
    * None
- **Improvements**: 
    * Rectangular prisms for incomplete stabilizers
- **Documentation changes**:
    * None

## Example usage and tests

![image](https://user-images.githubusercontent.com/675763/168157094-c9ef1a29-e568-47bc-8481-6e64f36c0eb1.png)

## Performance results justifying changes

- [x] Not Applicable

## Workflow actions and tests

- [x] Not Applicable

## Expected benefits and drawbacks

**Expected benefits:**
- Better visualization of stabilizers.

**Possible drawbacks:**
- None

## Related Github issues

- [x] Not Applicable

## Checklist and integration statements

- [ ] My Python and C++ codes follow the coding and commenting styles of this project as indicated by existing files. Specifically, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [ ] I have performed a self-review of these changes, checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [ ] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage 95% or better, and these pass locally for me.
- [ ] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

2022-05-18 14:53 UTC, nariman87 commented
This needs more discussion to give users the option to swap axes and observe possible bugs.

2022-06-10 03:49 UTC, nariman87 commented
> Talking with @ilan-tz and @soosub after our meeting, we think that it would be nice to have the draw function work even when there are no bit values defined in the cluster state. For example, a solution could be drawing grey boxes rather than green or red boxes whenever the weights have not been assigned. It would be nice if this enhancement is included in this PR!

Thanks for the new changes @sduquemesa, looking fantastic.

@BestQuark, based on your comment above, are you happy to review this PR as the next step?

2022-06-10 18:32 UTC, BestQuark reviewed
( [see review here]((https://github.com/XanaduAI/flamingpy/pull/35#issuecomment-1152625329) )

2022-06-14 20:43 UTC, BestQuark approved these changes
Great PR! everything looks good to me. 

(Before mergin, can we quickly change line 374 of `viz.py` from 
`ax.scatter(x, y, z, c=color)` to `ax.scatter(x, y, z, c=color, s=4)`? I think this would make the plots a bit sharper).

2022-06-14 22:03 UTC, ilan-tz requested changes
Really nice visual change here -- looks superb! Just to confirm: the issue with the x, y, z order in the stabilizer placement was fixed since our discussion, right? 

Unrelated to this PR, I think there is still an issue in some places with the x, y, z order -- e.g. the matching plot:

![Figure_17](https://user-images.githubusercontent.com/57886357/173694504-f4d2613b-be7a-4f2f-9756-88e19e370395.png)

Could you please sweep through the viz file to see wherever else it may still be a problem?

2022-06-14 22:03 UTC, ilan-tz commented on flamingpy/utils/viz.py
> +    is_incomplete_stab = len(cube_coords) != len(cube.physical)
```suggestion
    is_incomplete_stab = len(cube_coords) != 6
```

2022-06-14 22:03 UTC, ilan-tz commented on flamingpy/utils/viz.py
> +        # to do so the cube is tranlated to the origin of coordinates
```suggestion
        # Translate the cube to the origin
```

2022-06-14 22:03 UTC, ilan-tz commented on flamingpy/utils/viz.py
> +        # then stabilizers are paired (meaning 2 stabilizers) by finding the number
```suggestion
        #  Pair the stabilizers by finding the number
```

2022-06-15 16:08 UTC, sduquemesa commented on flamingpy/codes/stabilizer.py
> +        par = int(np.sum(bit_vals) % 2) if len(bit_vals) > 0 else None
Perfect, great suggestion! I have implemented it with a slight change.

2022-06-15 17:12 UTC, sduquemesa commented on flamingpy/codes/stabilizer.py
> +        par = int(np.sum(bit_vals) % 2) if len(bit_vals) > 0 else None
Actually, your suggestion worked better than mine 🤭

2022-06-15 17:26 UTC, sduquemesa commented
Thanks @ilan-tz and @BestQuark!

> Just to confirm: the issue with the x, y, z order in the stabilizer placement was fixed since our discussion, right?
> Unrelated to this PR, I think there is still an issue in some places with the x, y, z order
> Could you please sweep through the viz file to see wherever else it may still be a problem?

I reviewed the file and changed/commented where necessary. Please check if the issues you encountered were fixed.

![image](https://user-images.githubusercontent.com/675763/173888523-da914cb3-71b4-459f-8d29-a659041b03a6.png)

> Before merging, can we quickly change line 374 of viz.py from `ax.scatter(x, y, z, c=color)` to `ax.scatter(x, y, z, c=color, s=4)` (or some small number to reduce the size of the egraph nodes)? I think this would make the plots a bit sharper.

Done! See the size of the nodes in the image above 🎱

2022-06-16 22:44 UTC, ilan-tz commented
> Thanks @ilan-tz and @BestQuark!
> 
> > Just to confirm: the issue with the x, y, z order in the stabilizer placement was fixed since our discussion, right?
> > Unrelated to this PR, I think there is still an issue in some places with the x, y, z order
> > Could you please sweep through the viz file to see wherever else it may still be a problem?
> 
> I reviewed the file and changed/commented where necessary. Please check if the issues you encountered were fixed.
> 
> ![image](https://user-images.githubusercontent.com/675763/173888523-da914cb3-71b4-459f-8d29-a659041b03a6.png)
> 
> > Before merging, can we quickly change line 374 of viz.py from `ax.scatter(x, y, z, c=color)` to `ax.scatter(x, y, z, c=color, s=4)` (or some small number to reduce the size of the egraph nodes)? I think this would make the plots a bit sharper.
> 
> Done! See the size of the nodes in the image above 🎱

Looks nice! There is a small thing left to address:

- Have a look at the matching on the top-right (purple line). The left endpoint looks good, because it aligns with the middle of the stabilizer. However, the right endpoint sticks out, because it is being told to scatter at the midpoint of a complete stabilizer. Instead, it might look better if it terminates at the midpoint of an incomplete stabilizer (modification to line 826 of `viz.py`, or to the methods of the `Stabilizer` class (modify the `midpoint `method or add a a new method).
- The matching on the bottom left has the same issue. But since it starts at a boundary point, if we implement the above, the matching will go "diagonally" into the new midpoint. This might be okay! We will have to see how it looks.

2022-06-21 21:00 UTC, sduquemesa commented
Hey @ilan-tz, this is how it looks like when I apply the (not yet committed) changes

![image](https://user-images.githubusercontent.com/675763/174896299-11d6a2c6-455e-4692-9106-502848a539c1.png)

What do you think? I feel it looks good between stabilizers (upper line) but a bit weird for node-to-stabilizer (lower diagonal line).

2022-06-22 19:58 UTC, sduquemesa commented
After some more tweaking, this is how the end result looks like

![image](https://user-images.githubusercontent.com/675763/175124753-9bd96197-264c-4f7b-8479-823fc5a767a6.png)

The logic for drawing lines is the following

* If points belong to stabilizers, draw a line between the center of the stabilizers. 
* If the a point belongs to a stabilizer and another point is a node in the graph (this is the case for errors on the boundaries) then a line is drawn going from the midpoint of the stabilizer to the midpoint of the face on that boundary (and marked with an X on the plot), and another dotted line is drawn going from the midpoint of the face to the qubit where the error occurred.

2022-06-29 17:01 UTC, ilan-tz commented
> After some more tweaking, this is how the end result looks like
> 
> [...]
> 
> The logic for drawing lines is the following
> 
> * If points belong to stabilizers, draw a line between the center of the stabilizers.
> * If the a point belongs to a stabilizer and another point is a node in the graph (this is the case for errors on the boundaries) then a line is drawn going from the midpoint of the stabilizer to the midpoint of the face on that boundary (and marked with an X on the plot), and another dotted line is drawn going from the midpoint of the face to the qubit where the error occurred.

Thanks @sduquemesa ! Looks nice, but when you have a moment, I think the following would be good to tweak:

- For the part ".. a line is drawn going from the midpoint of the stabilizer to the midpoint of the face on that boundary" there is some ambiguity. First is "that boundary" should never correspond to a plane along _z_ since we the _x_/_y_ directions correspond to the 2D code boundaries. Second -- let us say you have a node on the corner. That could correspond to the _x_ or _y_ boundary of the lattice. This can be decided based on `SurfaceCode.ec` -- "primal" corresponds to _x_ and "dual" to _y_.
- I am seeing the following issue, where the X is not on the boundary but in the middle:

![image](https://user-images.githubusercontent.com/57886357/176493990-ea23c282-c670-4e1f-b063-9cb6b7cd08c2.png)

2022-11-23 18:00 UTC, closed without merging