Add figure to return statement of `draw` method of `EGraph`
XanaduAI/flamingpy pull request #55
Opened 2022-05-25 16:43 UTC by soosub

## Context for changes

Analogous to #33, it is useful to return the figure object to the user. This PR adds the figure object to return statement of `draw` method of `EGraph`.

- **Improvements**::
    * Figure object included in return statement of `EGraph.draw`
- **Documentation changes**:
    - [ ] added documentation for the relevant methods

## Example usage and tests

< Add some example usage and tests showing how to utilize new features and fixes; otherwise, mark N/A below. >
- [x] Not Applicable

## Performance results justifying changes

- [ ] Not Applicable

## Workflow actions and tests

< In most cases, we need a set of unit tests that automatically and comprehensively test for newly added features. Discuss existing CI tests that cover the changes or any updates to the workflow here; otherwise, mark N/A below. >

- [ ] Not Applicable

## Expected benefits and drawbacks

**Expected benefits:**
- Allows user more flexibility with using the figure and saving it for example.

**Possible drawbacks:**
- Unforeseen changes where the return of the current implementation is used. Can easily be adjusted by simply using the second index of the new return tuple.

## Related Github issues
#46 

## Checklist and integration statements

- [ ] My Python and C++ codes follow the coding and commenting styles of this project as indicated by existing files. Specifically, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [ ] I have performed a self-review of these changes, checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [ ] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage 95% or better, and these pass locally for me.
- [ ] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

2022-06-03 18:17 UTC, soosub commented
@ilan-tz during the writing of `test_draw` I noticed that the user is allowed to make an EGraph where the nodes are not given as (x,y,z) coordinates. Should we continue allowing this or force the user specify the nodes as a 3-tuple in the EGraph? This is mainly a problem for the corresponding draw method

2022-06-03 18:24 UTC, ilan-tz commented
> @ilan-tz during the writing of `test_draw` I noticed that the user is allowed to make an EGraph where the nodes are not given as (x,y,z) coordinates. Should we continue allowing this or force the user specify the nodes as a 3-tuple in the EGraph? This is mainly a problem for the corresponding draw method

The EGraph can work with any kind of hashable node since it's a NetworkX graph. However, most methods and most FP functionality does not make sense for non-tuple nodes, so I think it makes sense for us to enforce 3-tuples.

2022-06-03 18:26 UTC, soosub commented
> > @ilan-tz during the writing of `test_draw` I noticed that the user is allowed to make an EGraph where the nodes are not given as (x,y,z) coordinates. Should we continue allowing this or force the user specify the nodes as a 3-tuple in the EGraph? This is mainly a problem for the corresponding draw method
> 
> The EGraph can work with any kind of hashable node since it's a NetworkX graph. However, most methods and most FP functionality does not make sense for non-tuple nodes, so I think it makes sense for us to enforce 3-tuples.

Alright, then I'll make an issue out of it 👍🏼

2022-06-03 18:32 UTC, ilan-tz requested changes
Nice! Only very minor comments.

2022-06-03 18:32 UTC, ilan-tz commented on .github/CHANGELOG.md
> +* Added `fig, ax` returns for the draw methods in `utils/viz.py`.
```suggestion
* Added `fig, ax` returns for the draw methods in `utils/viz.py`.  [#55](https://github.com/XanaduAI/flamingpy/pull/55)
```

2022-06-03 18:32 UTC, ilan-tz commented on tests/unit/test_graphstates.py
> +    def test_draw(self):
In reality this is testing the draw_EGraph in the viz module, so we should move this tests to the viz test files.

2022-06-03 19:21 UTC, ilan-tz commented on tests/unit/test_viz.py
> +    """Tests for EGraphs."""
```suggestion
    """Tests for visualizing EGraphs."""
```

2022-06-07 15:15 UTC, ilan-tz approved these changes

2022-06-07 15:15 UTC, merged