Skip cpp-dependent tests when dependencies not installed
XanaduAI/flamingpy pull request #65
Opened 2022-05-27 20:10 UTC by sduquemesa

## Context for changes

Having the cpp dependecies installed is not a requirement to use and develop FlamingPy

- **Improvements**: 
    * Skip tests that require cpp libraries which make the test suite fail if not installed

## Example usage and tests

- [x] Not Applicable

## Performance results justifying changes

- [ ] Not Applicable

## Workflow actions and tests

- [ ] Not Applicable

## Expected benefits and drawbacks

**Expected benefits:**
- Devs won't have breaking test to later figure out is because the cpp libraries are not intalled (which are not a hard requirement)
**Possible drawbacks:**
- None

## Related Github issues

- [ ] Not Applicable

## Checklist and integration statements

- [ ] My Python and C++ codes follow this project's coding and commenting styles as indicated by existing files. Precisely, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [ ] I have performed a self-review of these changes, checked my code (including for [codefactor](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) compliance), and corrected misspellings to the best of my capacity. I have synced this branch with others as required.
- [ ] I have added context for corresponding changes in documentation and [`README.md`](README.md) as needed.
- [ ] I have added new workflow CI tests for corresponding changes, ensuring codecoverage is 95% or better, and these pass locally for me.
- [ ] I have updated [`CHANGELOG.md`](.github/CHANGELOG.md) following the template. I recognize that the developers may revisit [`CHANGELOG.md`](.github/CHANGELOG.md) and the versioning, and create a Special Release including my changes.

2022-06-01 00:11 UTC, nariman87 commented
This needs syncing with the latest `main`. Let me try to do that.

2022-06-01 00:50 UTC, nariman87 requested changes

2022-06-01 00:50 UTC, nariman87 commented on tests/unit/test_viz.py
> +import flamingpy.utils.viz as viz
Excellent work, @sduquemesa. Can you just briefly clarify why this change was needed here? Matter of better conventions?

2022-06-08 19:08 UTC, ilan-tz approved these changes
This is a very helpful fix, thank you!

2022-06-08 19:17 UTC, ilan-tz approved these changes

2022-06-08 19:20 UTC, merged