Pauli noise
XanaduAI/flamingpy pull request #8
Opened 2022-04-01 16:15 UTC by maxtremblay

## Context for changes

This add a new noise model sampling i.i.d Z error for each qubit.

## Example usage and tests

See the newly added test for an example.

## Performance results justifying changes

- [x] Not Applicable

## Workflow actions and tests

I added a few tests in test_iid_noise.py. 

## Expected benefits and drawbacks

It is a new noise model. There should be not drawbacks since it is completely optional.

## Related Github issues

- [x] Not Applicable

## Checklist and integration statements

- [x] My Python and C++ codes follow the coding and commenting styles of this project as indicated by existing files. Specifically, the changes conform to given `black`, `docformatter` and `pylint` configurations. 
- [x] I have performed a self-review of these changes. I have checked my code and corrected misspellings to the best of my capacity. I have checked the [CodeFactor score](https://www.codefactor.io/repository/github/xanaduai/flamingpy/branches) in the active branch and ensured it is `B-` or higher. I also confirm that I have already merged other branches into this branch as required.
- [x] I have added context for corresponding changes in documentation and README.md as needed.
- [x] I have added new workflow CI tests for corresponding changes and these pass locally for me.
- [] I have updated `_version.py` based on [semantic versioning](https://semver.org/). I recognize that the developers may create a Special Release including my changes.

2022-04-01 16:16 UTC, maxtremblay commented
@nariman87 I wanted to update the version number, but I am a bit confused by the meaning of post1 in the version.

2022-04-01 18:00 UTC, ilan-tz requested changes
Excellent work! This will add a basic alternative noise model to FlamingPy's arsenal. Just a few changes before this can be merged.

- Unit weights are the default behaviour of weight_options, so no need to modify the decoder file.
- I think `pauli,py` can be deleted?
- Question about using 0.0 and 1.0 over 0 and 1.
- I have updated `examples/decoding.py ` to allow the user to experiment with the new noise model - you may wish to have a look at that.

2022-04-01 18:39 UTC, maxtremblay commented on flamingpy/decoders/decoder.py
> +            node_data["weight"] = 1
You are right. I removed that.

2022-04-01 18:39 UTC, maxtremblay commented on flamingpy/noise/iid.py
> +        error_probability (float): the probability of a Z error.
You don't like the long and clearer name? An user will rarely have to type the full name anyway.

2022-04-01 18:40 UTC, maxtremblay commented on flamingpy/noise/iid.py
> +        if error_probability < 0.0 or error_probability > 1.0:
This saves on conversion from int to float since error_probability is a float.

2022-04-01 18:43 UTC, maxtremblay commented on tests/unit/test_iid_noise.py
> +    noise = IidNoise(code, 0.0)
A probability is a float, not an integer.

2022-04-01 18:46 UTC, maxtremblay commented on tests/unit/test_iid_noise.py
> +    noise = IidNoise(code, 1.0)
See my answer above.

2022-04-01 18:48 UTC, maxtremblay commented on tests/unit/test_iid_noise.py
> +    noise = IidNoise(code, 0.1)
I added a small loop to check a few different probabilities.

2022-04-01 19:53 UTC, ilan-tz commented on flamingpy/decoders/decoder.py
> +        weight_options (dict or str, optional): how to assign weights; options are
```suggestion
        weight_options (dict, optional): how to assign weights; options are

```

2022-04-01 20:44 UTC, ilan-tz commented on flamingpy/noise/iid.py
> +        This fixes the "bit_val" attribute of each nodes in the code egraph.
```suggestion
        This fixes the "bit_val" attribute of each node in the code egraph.
```

2022-04-01 21:58 UTC, nariman87 commented
> @nariman87 I wanted to update the version number, but I am a bit confused by the meaning of post1 in the version.
> 

post stands for post-release fixes not affecting the released version in a major way.

If your changes are some minor fixes we forgot for release, you may increase that to post2. I guess that's not your case here. So, you just delete that post1 and change the versioning as usual, @maxtremblay .

2022-04-02 18:54 UTC, maxtremblay commented
@nariman87 
I changed the version from 0.4.10a1.post1 to 0.4.10a2. Is that correct?

2022-04-02 22:33 UTC, nariman87 commented
> @nariman87 I changed the version from 0.4.10a1.post1 to 0.4.10a2. Is that correct? Or should I go directly to 0.4.11?

Thanks, @maxtremblay. We should certainly increase the first three version numbers. The great work you did here certainly appear to be a new feature. Is the new noise model fully backward compatible? If yes, please change it to "0.5.0", if no, to "1.0.0". We should keep alpha or beta versioning as well. Are we still considering this our 1st alpha? I assume this will be our second and new alpha with multiple noise models, so maybe "0.5.0a2".

2022-04-04 18:01 UTC, ilan-tz approved these changes

2022-04-04 18:03 UTC, merged